### ISSUE TITLE
issue with shell and Max 7

### ISSUE THREAD

**Issue by skrinsky** [jeremybernstein/shell#3]
Trying to run a python file from Max, wasn't sure if the issue was that it was a python file so i made a shell file that runs the python file. Still unable to get shell object to work- wondering what the directory path on the message should look like and if that is where I am running into issues? I've tried a number of things 
python "Macintosh HD:/Users/myname/webscrapes/headlines.py" 
or
~/webscrapes/headlines.sh
or 
~/myname/webscrapes/headlines.sh
or 
$myname ~/webscrapes/headlines.sh

or 
$myname ~/webscrapes/./headlines.sh 

etc.

**Comment by jeremybernstein** [comment]
You need to send messages to the shell object as if you were writing the message in the Terminal (+ escaping the \ character). So `python /Users/myname/webscrapes/headlines.py` should work (assuming that python is in your $PATH, otherwise you'll need to provide an absolute path to the python binary). Your `~/webscrapes/headlines.sh` should work, too, if your shell script is executable (with f.e. `chmod +x ~/webscrapes/headlines.sh`).

**Comment by skrinsky** [comment]
Neither of those worked, I'm wondering if it is a 32 bit/64 bit issue? Because I am in Max 7 which is 32 bit. Is there a 32 bit pre-update version of shell I should be using? Because the shell script and python scripts I wrote both execute without any problems when I write them straight into terminal

**Comment by jeremybernstein** [comment]
closing in absence of follow-up
